### ISSUE TITLE
Hide comments

### ISSUE THREAD

**Issue by oiva** [ludw1gj/distraction-blocker-for-youtube#2]
Thanks for this useful extension. Any chance of hiding the comments section too? Having comments visible makes Youtube like 20% more annoying to use.

**Comment by ludw1gj** [comment]
Hey @oiva,

I'm not planning to add any features to the extension as Apple is beginning the process of deprecating the platform (Safari Extensions Gallery) in favour for installing extensions via the App Store. I would like to get around releasing an updated version to the App Store in a couple of months when life settles down. When I do that, I'll bake in a couple of options including hiding comments. I use [Shut Up](https://rickyromero.com/shutup/) browser extension at the moment to hide comments, so it might solve your issue in the meantime.

Cheers.

**Comment by oiva** [comment]
That does the job, thanks!
