### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by dylanrmurphy** [ludw1gj/distraction-blocker-for-youtube#3]
Hi. How do I download because when I press the link for safari it just redirects me to the App Store page of all of the extensions?

**Comment by ludw1gj** [comment]
Hi,

This is now a legacy extension and no longer supported by Safari 13 or newer. Apple deprecated the platform (Safari Extensions Gallery) in favour for installing extensions via the App Store. I may get around releasing an updated version to the App Store in the future. The meantime I will remove the dead Link from this Github page.

Cheers.
